# Generated by Django 3.0.1 on 2019-12-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftMana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=4)),
                ('work_state', models.CharField(max_length=200)),
                ('work_shift', models.CharField(max_length=200)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiftMana.Schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkShift',
        ),
        migrations.DeleteModel(
            name='WorkState',
        ),
        migrations.AddField(
            model_name='account',
            name='work_shift',
            field=models.CharField(default='morning', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='work_state',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='00000', max_length=200),
        ),
    ]
