# Generated by Django 3.0.1 on 2019-12-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftMana', '0003_auto_20191224_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstate',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
