# Generated by Django 3.0.1 on 2019-12-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paycheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hour', models.IntegerField(default=0)),
                ('deduction', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedulestate',
            name='schedule',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='bonus',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='account',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='account',
            name='health_insurance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='account',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='account',
            name='work_duration',
        ),
        migrations.DeleteModel(
            name='ApplicationState',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleState',
        ),
        migrations.AddField(
            model_name='paycheck',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paroll.Account'),
        ),
    ]
