# Generated by Django 3.0.1 on 2019-12-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paroll', '0003_auto_20191225_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='identity',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
