# Generated by Django 3.0.1 on 2019-12-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paroll', '0004_account_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identity',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
